### Number Library

In [5]:
import numpy as np

li = [1,2,3,'z']
a = np.array(li)
a
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
m3 = np.random.randint(0,2,size=(3,3,3,3,3))
m3[2][2][2]
m3.ndim
m3.shape
m3.size
m3.itemsize
#m3.nbytes
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [70]:
m3 = np.random.randint(0,2,size=(3,3,3))
m3
m3.ndim # Array Dimension
m3.size # No.of Elements in an array
m3.shape # shape
m3.dtype
m3.itemsize

4

In [75]:
c = b.reshape(5,3)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [76]:
d = c + 1
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [106]:
import numpy as np
M = np.ones((3, 3))
print("Matrix M:\n",M)

Matrix M:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Pandas
 * Use Cases

 * Data Cleaning
 * Data Transformation
 * Data Analysis
 * Notations

* Series
* DataFrames

In [86]:
import pandas as pd
internal1 = {'s1':21, 's2':18, 's3':24}

internal1 = pd.Series(internal1)
internal1

internal2 = {'s1':15, 's2':18, 's3':12}
internal2 = pd.Series(internal2)
internal2



s1    15
s2    18
s3    12
dtype: int64

In [88]:
final = {'Internal1':internal1, 'Internal2':internal2}

final = pd.DataFrame(final)
final['Internal1']
final['Internal2']

s1    15
s2    18
s3    12
Name: Internal2, dtype: int64

In [90]:
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [91]:
final.columns

Index(['Internal1', 'Internal2'], dtype='object')

In [94]:
s = final.values

In [95]:
print(s)

[[21 15]
 [18 18]
 [24 12]]


In [96]:
final.values[2]

array([24, 12], dtype=int64)

In [99]:
final.values[2,0]
final.values[2][0]

24

In [100]:
for row in final.values:
    print('Internal1 - ',row[0],', Internal2 - ',row[1])

Internal1 -  21 , Internal2 -  15
Internal1 -  18 , Internal2 -  18
Internal1 -  24 , Internal2 -  12


In [101]:
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [102]:
final.loc['s4'] = [20, 18]
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12
s4         20         18

In [105]:
final.drop(s3)
final

NameError: name 's3' is not defined